//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "PWM.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "driverlib/pwm.h"    //Added after pinmux
#include "inc/tm4c123gh6pm.h" //Added after pinmux

//*****************************************************************************



void
PWM_Init(void)
{
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_PWM1);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF3 for PWM1 M1PWM7
    //
    GPIOPinConfigure(GPIO_PF3_M1PWM7); //green
    GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_3);

    //
    // Enable pin PF1 for PWM1 M1PWM5
    //
    GPIOPinConfigure(GPIO_PF1_M1PWM5); //red
    GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF2 for PWM1 M1PWM6
    //
    GPIOPinConfigure(GPIO_PF2_M1PWM6); //blue
    GPIOPinTypePWM(GPIO_PORTF_BASE, GPIO_PIN_2);

///////// Above: PinMUX, Below: added by programer
		//Enable pull-up on PF0,4 for buttons
		GPIO_PORTF_PUR_R |= 0x11; 
		
		//PWM Setup
		//Each generater is connected to two pins, PWM6&7 are on gen3, while PWM5 is on gen2
		//// Configure the PWM generator for count down mode with immediate updates// to the parameters.//
		PWMGenConfigure(PWM1_BASE, PWM_GEN_2,PWM_GEN_MODE_DOWN | PWM_GEN_MODE_NO_SYNC); //red
		PWMGenPeriodSet(PWM1_BASE, PWM_GEN_2, 512); //freq 1/512 of system, and range for widthSet
		PWMGenConfigure(PWM1_BASE, PWM_GEN_3,PWM_GEN_MODE_DOWN | PWM_GEN_MODE_NO_SYNC); //blue and green
		PWMGenPeriodSet(PWM1_BASE, PWM_GEN_3, 512);
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_5, 1);//red (1 off 512 max), do not set as 0
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_6, 1);//blue
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_7, 1);//green
		PWMGenEnable(PWM1_BASE, PWM_GEN_2);// once setup, enable generators
		PWMGenEnable(PWM1_BASE, PWM_GEN_3);
		PWMOutputState(PWM1_BASE, (PWM_OUT_5_BIT | PWM_OUT_6_BIT | PWM_OUT_7_BIT), true);
}

// If PWM value is outside valid range, sets PWM value to be min/max
int Check_PWM_Range(int led) {\
	if (led > 512)
		return 512;
	else if (led < 1)
		return 1;
	
	return led;
}

// Update LEDs using PWM
void Update_PWM(int r,int g,int b){
	
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_5, Check_PWM_Range(r));//red (Range: 1 off-512 max)
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_7, Check_PWM_Range(g));//green
		PWMPulseWidthSet(PWM1_BASE, PWM_OUT_6, Check_PWM_Range(b));//blue, setting 0 here can cause 100% power, so +1
	
}
